- hosts: all
  tasks:
      - name: print hello
        shell: echo "hello world" 
        register: helo

      - name: Print helo
        debug:
          msg: "helo output: {{ helo.stdout }}, vault pass: {{ vault_ansible_password }}"
          
